-- ============================================================
-- Verified Food Database V2 — Fitness Staples + Egyptian Restaurants
-- Adds serving_type column, replaces duplicates, inserts all foods
-- ============================================================

-- Step 1: Add serving_type column if it doesn't exist
ALTER TABLE public.food_inventory ADD COLUMN IF NOT EXISTS serving_type text DEFAULT 'per_100g';

-- Step 2: Update the source constraint to allow the new source values
ALTER TABLE public.food_inventory DROP CONSTRAINT IF EXISTS food_inventory_source_check;

-- Step 3: Delete ALL existing presets that will be replaced
-- This includes both old names (from previous batch) and new names (from this batch)
DELETE FROM public.food_inventory WHERE source = 'preset' AND name IN (
  -- Old names from previous batch that are being renamed/replaced
  'Eggs (Raw, Whole)', 'Oats (Rolled, Dry)', 'Greek Yogurt (Non-fat, Plain)',
  'Cottage Cheese (Low Fat, 2%)', 'Peanut Butter (Natural, No Sugar)',
  'Almond Butter (Plain)', 'Tofu (Firm)', 'Flaxseed (Ground)',
  'Macaroni / Pasta (Raw)', 'Macaroni / Pasta (Cooked)',
  'Ghee (Clarified Butter)', 'Apple (Raw, with skin)', 'Mozzarella (Part Skim)',
  'Potato (Raw, with skin)', 'Potato (Baked, flesh & skin)',
  'Chicken Breast (Cooked, Roasted)', 'Beef (Ground, 95% Lean, Raw)',
  'Beef (Ground, 80% Lean, Raw)', 'Beef Steak (Sirloin, Raw)',
  'Beef Steak (Ribeye, Raw)', 'Pork Chop (Lean, Raw)',
  'Salmon (Atlantic, Raw)', 'Flour Tortilla', 'Corn Tortilla',
  'Sardines (Canned in Oil)',

  -- New names from this batch (exact match delete)
  'Chicken Breast (Raw, Skinless)', 'Chicken Breast (Cooked, Grilled)',
  'Chicken Thigh (Raw, Skinless)', 'Turkey Breast (Raw, Skinless)',
  'Turkey Breast (Cooked)', 'Beef (95% Lean Ground, Raw)',
  'Beef (90% Lean Ground, Raw)', 'Beef (80% Lean Ground, Raw)',
  'Beef Sirloin Steak (Raw)', 'Beef Ribeye Steak (Raw)',
  'Bison/Buffalo (Raw, Lean)', 'Pork Tenderloin (Raw)',
  'Salmon (Raw, Atlantic)', 'Tuna (Canned in Water, Drained)',
  'Tuna (Fresh, Raw)', 'Tilapia (Raw)', 'Cod (Raw)', 'Shrimp (Raw)',
  'Sardines (Canned in Water)', 'Mackerel (Raw)',
  'Egg Whites (Raw)', 'Whole Eggs (Raw)',
  'Greek Yogurt (Non-fat, 0%)', 'Cottage Cheese (Low-fat, 2%)',
  'Whey Protein Isolate (Dry Powder)', 'Casein Protein (Dry Powder)',
  'Tofu (Extra Firm)', 'Tempeh', 'Seitan',
  'White Rice (Raw)', 'White Rice (Cooked)',
  'Basmati Rice (Raw)', 'Basmati Rice (Cooked)',
  'Brown Rice (Raw)', 'Brown Rice (Cooked)',
  'Rolled Oats (Dry)', 'Quick Oats (Dry)',
  'Pasta / Macaroni (Raw)', 'Pasta / Macaroni (Cooked)',
  'Whole Wheat Pasta (Raw)',
  'Potato (Raw)', 'Potato (Baked, with skin)',
  'Sweet Potato (Raw)', 'Sweet Potato (Baked)',
  'Quinoa (Dry)', 'Quinoa (Cooked)', 'Couscous (Dry)',
  'Lentils (Dry)', 'Lentils (Cooked)',
  'Chickpeas (Dry)', 'Chickpeas (Cooked)', 'Chickpeas (Cooked/Canned)',
  'Black Beans (Dry)', 'Black Beans (Cooked)',
  'White Bread', 'Whole Wheat Bread',
  'Rice Cakes (Plain)', 'Tortilla (Flour)', 'Tortilla (Corn)',
  'Banana (Raw)', 'Apple (Raw)', 'Blueberries (Raw)',
  'Dates (Medjool)', 'Honey',
  'Olive Oil (Extra Virgin)', 'Coconut Oil', 'Butter (Salted)',
  'Ghee', 'Avocado (Raw)',
  'Peanut Butter (Natural)', 'Almond Butter',
  'Almonds (Raw)', 'Walnuts (Raw)', 'Cashews (Raw)',
  'Chia Seeds', 'Flaxseeds', 'Hemp Seeds',
  'Cheddar Cheese', 'Mozzarella (Part-Skim)',

  -- Restaurant / Fast Food names
  'Big Mac (McDonald''s)', 'Big Tasty Beef (McDonald''s)',
  'Double Big Tasty (McDonald''s)', 'McRoyale (McDonald''s)',
  'Double McRoyale (McDonald''s)', 'Cheeseburger (McDonald''s)',
  'Double Cheeseburger (McDonald''s)', 'Beefburger (McDonald''s)',
  'McChicken (McDonald''s)', 'Double McChicken (McDonald''s)',
  'Grand Chicken Premier (McDonald''s)', 'Grand Chicken Spicy (McDonald''s)',
  'Big Tasty Chicken (McDonald''s)', 'Chicken MACDO (McDonald''s)',
  'Filet-O-Fish (McDonald''s)',
  'French Fries - Regular (McDonald''s)', 'French Fries - Large (McDonald''s)',
  'Zinger Burger (KFC)', 'Mighty Zinger Burger (KFC)',
  'Twister Sandwich (KFC)', 'Original Recipe Chicken - Breast (KFC)',
  'Original Recipe Chicken - Thigh (KFC)', 'Original Recipe Chicken - Drumstick (KFC)',
  'Spicy/Crispy Chicken - Breast (KFC)', 'Fries - Medium (KFC)',
  'Rizo with Chicken Pieces (KFC)',
  'Old School Burger - 150g Patty (Buffalo Burger)',
  'Bacon Mushroom Jack - 150g Patty (Buffalo Burger)',
  'Charbroiled BBQ Burger - 150g Patty (Buffalo Burger)',
  'Cholo''s Burger - 150g Patty (Buffalo Burger)',
  'Cheesy Fries (Buffalo Burger)',
  'Koshary - Per 100g (Egyptian Street Food)',
  'Koshary - Standard Bowl 300g (Koshary El Tahrir/Abou Tarek)',
  'Koshary - Large Bowl 500g',
  'Foul Medames Sandwich (Egyptian Street Food)',
  'Taameya / Falafel Sandwich (Egyptian Street Food)',
  'Shawarma Meat Sandwich - Kaiser (Egyptian)',
  'Shawarma Chicken Sandwich - Kaiser (Egyptian)',
  'Hawawshi - Whole Loaf (Egyptian Street Food)',
  'Shish Tawook Sandwich (Egyptian)',
  'Molokhia - Per 100g Cooked',
  -- Ibn Al Sham
  'Chicken Shawarma Saj - Large (Ibn Al Sham)',
  'Meat Shawarma Saj - Large (Ibn Al Sham)',
  'Arabian Chicken Shawarma Meal (Ibn Al Sham)',
  'Half Grilled Chicken + Rice (Ibn Al Sham)',
  'Shish Tawook Breast Platter (Ibn Al Sham)',
  'Crispy Chicken Meal - 5 Pcs (Ibn Al Sham)'
);


-- ═══════════════════════════════════════════════════════════
-- Step 4: INSERT ALL FOODS
-- ═══════════════════════════════════════════════════════════

-- ═══════════════ PROTEINS (FITNESS) — per 100g ═══════════════
INSERT INTO public.food_inventory (user_id, name, category, kcal_per_100g, protein, carbs, fat, source, serving_type) VALUES
(NULL, 'Chicken Breast (Raw, Skinless)',     'Proteins (Fitness)', 120, 22.5, 0, 2.6, 'preset', 'per_100g'),
(NULL, 'Chicken Breast (Cooked, Grilled)',   'Proteins (Fitness)', 165, 31.0, 0, 3.6, 'preset', 'per_100g'),
(NULL, 'Chicken Thigh (Raw, Skinless)',      'Proteins (Fitness)', 135, 19.5, 0, 5.7, 'preset', 'per_100g'),
(NULL, 'Turkey Breast (Raw, Skinless)',      'Proteins (Fitness)', 114, 23.7, 0, 1.5, 'preset', 'per_100g'),
(NULL, 'Turkey Breast (Cooked)',             'Proteins (Fitness)', 147, 30.1, 0, 1.7, 'preset', 'per_100g'),
(NULL, 'Beef (95% Lean Ground, Raw)',        'Proteins (Fitness)', 137, 21.4, 0, 5.0, 'preset', 'per_100g'),
(NULL, 'Beef (90% Lean Ground, Raw)',        'Proteins (Fitness)', 176, 20.0, 0, 10.0, 'preset', 'per_100g'),
(NULL, 'Beef (80% Lean Ground, Raw)',        'Proteins (Fitness)', 254, 17.2, 0, 20.0, 'preset', 'per_100g'),
(NULL, 'Beef Sirloin Steak (Raw)',           'Proteins (Fitness)', 146, 21.6, 0, 5.9, 'preset', 'per_100g'),
(NULL, 'Beef Ribeye Steak (Raw)',            'Proteins (Fitness)', 291, 15.0, 0, 25.0, 'preset', 'per_100g'),
(NULL, 'Bison/Buffalo (Raw, Lean)',          'Proteins (Fitness)', 109, 21.6, 0, 1.8, 'preset', 'per_100g'),
(NULL, 'Pork Tenderloin (Raw)',              'Proteins (Fitness)', 120, 21.1, 0, 3.3, 'preset', 'per_100g'),
(NULL, 'Salmon (Raw, Atlantic)',             'Proteins (Fitness)', 208, 20.4, 0, 13.4, 'preset', 'per_100g'),
(NULL, 'Tuna (Canned in Water, Drained)',    'Proteins (Fitness)', 116, 25.5, 0, 0.8, 'preset', 'per_100g'),
(NULL, 'Tuna (Fresh, Raw)',                  'Proteins (Fitness)', 144, 23.3, 0, 4.9, 'preset', 'per_100g'),
(NULL, 'Tilapia (Raw)',                      'Proteins (Fitness)', 96, 20.1, 0, 1.7, 'preset', 'per_100g'),
(NULL, 'Cod (Raw)',                          'Proteins (Fitness)', 82, 17.8, 0, 0.7, 'preset', 'per_100g'),
(NULL, 'Shrimp (Raw)',                       'Proteins (Fitness)', 85, 20.1, 0, 0.5, 'preset', 'per_100g'),
(NULL, 'Sardines (Canned in Water)',         'Proteins (Fitness)', 146, 21.0, 0, 6.0, 'preset', 'per_100g'),
(NULL, 'Mackerel (Raw)',                     'Proteins (Fitness)', 205, 18.6, 0, 13.9, 'preset', 'per_100g'),
(NULL, 'Egg Whites (Raw)',                   'Proteins (Fitness)', 52, 10.9, 0.7, 0.2, 'preset', 'per_100g'),
(NULL, 'Whole Eggs (Raw)',                   'Proteins (Fitness)', 143, 12.6, 0.7, 9.5, 'preset', 'per_100g'),
(NULL, 'Greek Yogurt (Non-fat, 0%)',         'Proteins (Fitness)', 59, 10.3, 3.6, 0.4, 'preset', 'per_100g'),
(NULL, 'Cottage Cheese (Low-fat, 2%)',       'Proteins (Fitness)', 82, 11.0, 4.3, 2.3, 'preset', 'per_100g'),
(NULL, 'Whey Protein Isolate (Dry Powder)',  'Proteins (Fitness)', 359, 81.0, 3.0, 1.0, 'preset', 'per_100g'),
(NULL, 'Casein Protein (Dry Powder)',        'Proteins (Fitness)', 360, 75.0, 8.0, 1.5, 'preset', 'per_100g'),
(NULL, 'Tofu (Extra Firm)',                  'Proteins (Fitness)', 144, 15.8, 2.8, 8.7, 'preset', 'per_100g'),
(NULL, 'Tempeh',                             'Proteins (Fitness)', 192, 20.3, 7.6, 10.8, 'preset', 'per_100g'),
(NULL, 'Seitan',                             'Proteins (Fitness)', 370, 75.0, 14.0, 1.9, 'preset', 'per_100g');

-- ═══════════════ CARBOHYDRATES (FITNESS) — per 100g ═══════════════
INSERT INTO public.food_inventory (user_id, name, category, kcal_per_100g, protein, carbs, fat, source, serving_type) VALUES
(NULL, 'White Rice (Raw)',                   'Carbohydrates (Fitness)', 365, 7.1, 80.0, 0.7, 'preset', 'per_100g'),
(NULL, 'White Rice (Cooked)',                'Carbohydrates (Fitness)', 130, 2.7, 28.0, 0.3, 'preset', 'per_100g'),
(NULL, 'Basmati Rice (Raw)',                 'Carbohydrates (Fitness)', 365, 7.1, 79.0, 0.6, 'preset', 'per_100g'),
(NULL, 'Basmati Rice (Cooked)',              'Carbohydrates (Fitness)', 121, 3.5, 25.2, 0.4, 'preset', 'per_100g'),
(NULL, 'Brown Rice (Raw)',                   'Carbohydrates (Fitness)', 367, 7.5, 76.2, 3.3, 'preset', 'per_100g'),
(NULL, 'Brown Rice (Cooked)',                'Carbohydrates (Fitness)', 112, 2.6, 23.5, 0.9, 'preset', 'per_100g'),
(NULL, 'Rolled Oats (Dry)',                  'Carbohydrates (Fitness)', 389, 16.9, 66.3, 6.9, 'preset', 'per_100g'),
(NULL, 'Quick Oats (Dry)',                   'Carbohydrates (Fitness)', 379, 13.1, 67.7, 6.5, 'preset', 'per_100g'),
(NULL, 'Pasta / Macaroni (Raw)',             'Carbohydrates (Fitness)', 371, 13.0, 74.7, 1.5, 'preset', 'per_100g'),
(NULL, 'Pasta / Macaroni (Cooked)',          'Carbohydrates (Fitness)', 157, 5.8, 30.7, 0.9, 'preset', 'per_100g'),
(NULL, 'Whole Wheat Pasta (Raw)',            'Carbohydrates (Fitness)', 348, 14.6, 71.3, 1.6, 'preset', 'per_100g'),
(NULL, 'Potato (Raw)',                       'Carbohydrates (Fitness)', 77, 2.0, 17.5, 0.1, 'preset', 'per_100g'),
(NULL, 'Potato (Baked, with skin)',          'Carbohydrates (Fitness)', 93, 2.5, 21.2, 0.1, 'preset', 'per_100g'),
(NULL, 'Sweet Potato (Raw)',                 'Carbohydrates (Fitness)', 86, 1.6, 20.1, 0.1, 'preset', 'per_100g'),
(NULL, 'Sweet Potato (Baked)',               'Carbohydrates (Fitness)', 90, 2.0, 20.7, 0.2, 'preset', 'per_100g'),
(NULL, 'Quinoa (Dry)',                       'Carbohydrates (Fitness)', 368, 14.1, 64.2, 6.1, 'preset', 'per_100g'),
(NULL, 'Quinoa (Cooked)',                    'Carbohydrates (Fitness)', 120, 4.4, 21.3, 1.9, 'preset', 'per_100g'),
(NULL, 'Couscous (Dry)',                     'Carbohydrates (Fitness)', 376, 12.8, 77.4, 0.6, 'preset', 'per_100g'),
(NULL, 'Lentils (Dry)',                      'Carbohydrates (Fitness)', 353, 24.6, 60.1, 1.1, 'preset', 'per_100g'),
(NULL, 'Lentils (Cooked)',                   'Carbohydrates (Fitness)', 116, 9.0, 20.1, 0.4, 'preset', 'per_100g'),
(NULL, 'Chickpeas (Dry)',                    'Carbohydrates (Fitness)', 378, 20.5, 63.0, 6.0, 'preset', 'per_100g'),
(NULL, 'Chickpeas (Cooked)',                 'Carbohydrates (Fitness)', 164, 8.9, 27.4, 2.6, 'preset', 'per_100g'),
(NULL, 'Black Beans (Dry)',                  'Carbohydrates (Fitness)', 341, 21.6, 62.4, 1.4, 'preset', 'per_100g'),
(NULL, 'Black Beans (Cooked)',               'Carbohydrates (Fitness)', 132, 8.9, 23.7, 0.5, 'preset', 'per_100g'),
(NULL, 'White Bread',                        'Carbohydrates (Fitness)', 265, 8.8, 49.0, 3.2, 'preset', 'per_100g'),
(NULL, 'Whole Wheat Bread',                  'Carbohydrates (Fitness)', 252, 12.4, 42.7, 3.5, 'preset', 'per_100g'),
(NULL, 'Rice Cakes (Plain)',                 'Carbohydrates (Fitness)', 387, 8.2, 81.5, 2.8, 'preset', 'per_100g'),
(NULL, 'Tortilla (Flour)',                   'Carbohydrates (Fitness)', 297, 8.0, 49.3, 7.5, 'preset', 'per_100g'),
(NULL, 'Tortilla (Corn)',                    'Carbohydrates (Fitness)', 218, 5.7, 45.4, 2.8, 'preset', 'per_100g'),
(NULL, 'Banana (Raw)',                       'Carbohydrates (Fitness)', 89, 1.1, 22.8, 0.3, 'preset', 'per_100g'),
(NULL, 'Apple (Raw)',                        'Carbohydrates (Fitness)', 52, 0.3, 13.8, 0.2, 'preset', 'per_100g'),
(NULL, 'Blueberries (Raw)',                  'Carbohydrates (Fitness)', 57, 0.7, 14.5, 0.3, 'preset', 'per_100g'),
(NULL, 'Dates (Medjool)',                    'Carbohydrates (Fitness)', 277, 1.8, 75.0, 0.2, 'preset', 'per_100g'),
(NULL, 'Honey',                              'Carbohydrates (Fitness)', 304, 0.3, 82.4, 0.0, 'preset', 'per_100g');

-- ═══════════════ FATS (FITNESS) — per 100g ═══════════════
INSERT INTO public.food_inventory (user_id, name, category, kcal_per_100g, protein, carbs, fat, source, serving_type) VALUES
(NULL, 'Olive Oil (Extra Virgin)',           'Fats (Fitness)', 884, 0, 0, 100.0, 'preset', 'per_100g'),
(NULL, 'Coconut Oil',                        'Fats (Fitness)', 862, 0, 0, 100.0, 'preset', 'per_100g'),
(NULL, 'Butter (Salted)',                    'Fats (Fitness)', 717, 0.8, 0.1, 81.1, 'preset', 'per_100g'),
(NULL, 'Ghee',                               'Fats (Fitness)', 900, 0, 0, 100.0, 'preset', 'per_100g'),
(NULL, 'Avocado (Raw)',                      'Fats (Fitness)', 160, 2.0, 8.5, 14.7, 'preset', 'per_100g'),
(NULL, 'Peanut Butter (Natural)',            'Fats (Fitness)', 588, 25.1, 20.0, 50.4, 'preset', 'per_100g'),
(NULL, 'Almond Butter',                     'Fats (Fitness)', 614, 21.0, 18.8, 55.5, 'preset', 'per_100g'),
(NULL, 'Almonds (Raw)',                      'Fats (Fitness)', 579, 21.1, 21.6, 49.9, 'preset', 'per_100g'),
(NULL, 'Walnuts (Raw)',                      'Fats (Fitness)', 654, 15.2, 13.7, 65.2, 'preset', 'per_100g'),
(NULL, 'Cashews (Raw)',                      'Fats (Fitness)', 553, 18.2, 30.2, 43.8, 'preset', 'per_100g'),
(NULL, 'Chia Seeds',                         'Fats (Fitness)', 486, 16.5, 42.1, 30.7, 'preset', 'per_100g'),
(NULL, 'Flaxseeds',                          'Fats (Fitness)', 534, 18.3, 28.9, 42.2, 'preset', 'per_100g'),
(NULL, 'Hemp Seeds',                         'Fats (Fitness)', 553, 31.6, 8.7, 48.8, 'preset', 'per_100g'),
(NULL, 'Cheddar Cheese',                     'Fats (Fitness)', 403, 24.9, 1.3, 33.1, 'preset', 'per_100g'),
(NULL, 'Mozzarella (Part-Skim)',             'Fats (Fitness)', 254, 24.3, 2.8, 15.9, 'preset', 'per_100g');

-- ═══════════════ EGYPTIAN RESTAURANTS & FAST FOOD — per item ═══════════════
INSERT INTO public.food_inventory (user_id, name, category, kcal_per_100g, protein, carbs, fat, source, serving_type) VALUES
-- McDonald's
(NULL, 'Big Mac (McDonald''s)',                        'Egyptian Restaurants & Fast Food', 537, 27.8, 52.4, 32.5, 'preset', 'per_item'),
(NULL, 'Big Tasty Beef (McDonald''s)',                  'Egyptian Restaurants & Fast Food', 947, 52.6, 56.8, 55.9, 'preset', 'per_item'),
(NULL, 'Double Big Tasty (McDonald''s)',                'Egyptian Restaurants & Fast Food', 1351, 85.3, 56.2, 85.9, 'preset', 'per_item'),
(NULL, 'McRoyale (McDonald''s)',                        'Egyptian Restaurants & Fast Food', 880, 47.4, 55.3, 51.4, 'preset', 'per_item'),
(NULL, 'Double McRoyale (McDonald''s)',                 'Egyptian Restaurants & Fast Food', 1351, 85.3, 56.2, 86.0, 'preset', 'per_item'),
(NULL, 'Cheeseburger (McDonald''s)',                    'Egyptian Restaurants & Fast Food', 305, 16.7, 34.0, 13.5, 'preset', 'per_item'),
(NULL, 'Double Cheeseburger (McDonald''s)',             'Egyptian Restaurants & Fast Food', 434, 28.1, 34.9, 25.2, 'preset', 'per_item'),
(NULL, 'Beefburger (McDonald''s)',                      'Egyptian Restaurants & Fast Food', 252, 14.1, 33.1, 9.4, 'preset', 'per_item'),
(NULL, 'McChicken (McDonald''s)',                       'Egyptian Restaurants & Fast Food', 750, 17.9, 56.3, 20.7, 'preset', 'per_item'),
(NULL, 'Double McChicken (McDonald''s)',                'Egyptian Restaurants & Fast Food', 1198, 26.9, 71.6, 30.1, 'preset', 'per_item'),
(NULL, 'Grand Chicken Premier (McDonald''s)',           'Egyptian Restaurants & Fast Food', 855, 47.1, 69.4, 44.1, 'preset', 'per_item'),
(NULL, 'Grand Chicken Spicy (McDonald''s)',             'Egyptian Restaurants & Fast Food', 799, 39.3, 71.8, 40.9, 'preset', 'per_item'),
(NULL, 'Big Tasty Chicken (McDonald''s)',                'Egyptian Restaurants & Fast Food', 867, 46.4, 70.5, 44.2, 'preset', 'per_item'),
(NULL, 'Chicken MACDO (McDonald''s)',                   'Egyptian Restaurants & Fast Food', 351, 13.1, 37.3, 16.4, 'preset', 'per_item'),
(NULL, 'Filet-O-Fish (McDonald''s)',                    'Egyptian Restaurants & Fast Food', 392, 18.6, 40.7, 17.0, 'preset', 'per_item'),
(NULL, 'French Fries - Regular (McDonald''s)',          'Egyptian Restaurants & Fast Food', 320, 4.0, 43.0, 15.0, 'preset', 'per_item'),
(NULL, 'French Fries - Large (McDonald''s)',            'Egyptian Restaurants & Fast Food', 510, 6.0, 67.0, 24.0, 'preset', 'per_item'),
-- KFC
(NULL, 'Zinger Burger (KFC)',                           'Egyptian Restaurants & Fast Food', 450, 23.0, 45.0, 19.0, 'preset', 'per_item'),
(NULL, 'Mighty Zinger Burger (KFC)',                    'Egyptian Restaurants & Fast Food', 780, 41.0, 65.0, 39.0, 'preset', 'per_item'),
(NULL, 'Twister Sandwich (KFC)',                        'Egyptian Restaurants & Fast Food', 410, 15.0, 42.0, 19.0, 'preset', 'per_item'),
(NULL, 'Original Recipe Chicken - Breast (KFC)',        'Egyptian Restaurants & Fast Food', 390, 39.0, 11.0, 21.0, 'preset', 'per_item'),
(NULL, 'Original Recipe Chicken - Thigh (KFC)',         'Egyptian Restaurants & Fast Food', 280, 19.0, 8.0, 19.0, 'preset', 'per_item'),
(NULL, 'Original Recipe Chicken - Drumstick (KFC)',     'Egyptian Restaurants & Fast Food', 130, 12.0, 4.0, 8.0, 'preset', 'per_item'),
(NULL, 'Spicy/Crispy Chicken - Breast (KFC)',           'Egyptian Restaurants & Fast Food', 530, 35.0, 22.0, 35.0, 'preset', 'per_item'),
(NULL, 'Fries - Medium (KFC)',                          'Egyptian Restaurants & Fast Food', 330, 4.0, 42.0, 16.0, 'preset', 'per_item'),
(NULL, 'Rizo with Chicken Pieces (KFC)',                'Egyptian Restaurants & Fast Food', 640, 22.0, 92.0, 20.0, 'preset', 'per_item'),
-- Buffalo Burger
(NULL, 'Old School Burger - 150g Patty (Buffalo Burger)',          'Egyptian Restaurants & Fast Food', 650, 42.0, 45.0, 35.0, 'preset', 'per_item'),
(NULL, 'Bacon Mushroom Jack - 150g Patty (Buffalo Burger)',        'Egyptian Restaurants & Fast Food', 780, 46.0, 46.0, 45.0, 'preset', 'per_item'),
(NULL, 'Charbroiled BBQ Burger - 150g Patty (Buffalo Burger)',     'Egyptian Restaurants & Fast Food', 690, 43.0, 52.0, 34.0, 'preset', 'per_item'),
(NULL, 'Cholo''s Burger - 150g Patty (Buffalo Burger)',            'Egyptian Restaurants & Fast Food', 710, 43.0, 46.0, 39.0, 'preset', 'per_item'),
(NULL, 'Cheesy Fries (Buffalo Burger)',                            'Egyptian Restaurants & Fast Food', 450, 10.0, 55.0, 23.0, 'preset', 'per_item'),
-- Egyptian Street Food
(NULL, 'Koshary - Per 100g (Egyptian Street Food)',                'Egyptian Restaurants & Fast Food', 155, 5.0, 28.0, 2.0, 'preset', 'per_100g'),
(NULL, 'Koshary - Standard Bowl 300g (Koshary El Tahrir/Abou Tarek)', 'Egyptian Restaurants & Fast Food', 465, 15.0, 84.0, 6.0, 'preset', 'per_item'),
(NULL, 'Koshary - Large Bowl 500g',                                'Egyptian Restaurants & Fast Food', 775, 25.0, 140.0, 10.0, 'preset', 'per_item'),
(NULL, 'Foul Medames Sandwich (Egyptian Street Food)',             'Egyptian Restaurants & Fast Food', 320, 12.0, 50.0, 8.0, 'preset', 'per_item'),
(NULL, 'Taameya / Falafel Sandwich (Egyptian Street Food)',        'Egyptian Restaurants & Fast Food', 380, 10.0, 45.0, 18.0, 'preset', 'per_item'),
(NULL, 'Shawarma Meat Sandwich - Kaiser (Egyptian)',               'Egyptian Restaurants & Fast Food', 450, 22.0, 35.0, 25.0, 'preset', 'per_item'),
(NULL, 'Shawarma Chicken Sandwich - Kaiser (Egyptian)',            'Egyptian Restaurants & Fast Food', 410, 25.0, 35.0, 18.0, 'preset', 'per_item'),
(NULL, 'Hawawshi - Whole Loaf (Egyptian Street Food)',             'Egyptian Restaurants & Fast Food', 600, 30.0, 45.0, 35.0, 'preset', 'per_item'),
(NULL, 'Shish Tawook Sandwich (Egyptian)',                         'Egyptian Restaurants & Fast Food', 350, 24.0, 40.0, 10.0, 'preset', 'per_item'),
(NULL, 'Molokhia - Per 100g Cooked',                               'Egyptian Restaurants & Fast Food', 45, 2.0, 5.0, 1.5, 'preset', 'per_100g'),
-- Ibn Al Sham
(NULL, 'Chicken Shawarma Saj - Large (Ibn Al Sham)',                'Egyptian Restaurants & Fast Food', 580, 38.0, 45.0, 26.0, 'preset', 'per_item'),
(NULL, 'Meat Shawarma Saj - Large (Ibn Al Sham)',                   'Egyptian Restaurants & Fast Food', 640, 35.0, 42.0, 36.0, 'preset', 'per_item'),
(NULL, 'Arabian Chicken Shawarma Meal (Ibn Al Sham)',               'Egyptian Restaurants & Fast Food', 1250, 52.0, 120.0, 62.0, 'preset', 'per_item'),
(NULL, 'Half Grilled Chicken + Rice (Ibn Al Sham)',                 'Egyptian Restaurants & Fast Food', 1020, 85.0, 68.0, 44.0, 'preset', 'per_item'),
(NULL, 'Shish Tawook Breast Platter (Ibn Al Sham)',                 'Egyptian Restaurants & Fast Food', 740, 68.0, 65.0, 20.0, 'preset', 'per_item'),
(NULL, 'Crispy Chicken Meal - 5 Pcs (Ibn Al Sham)',                 'Egyptian Restaurants & Fast Food', 1380, 65.0, 115.0, 74.0, 'preset', 'per_item');
