-- ============================================================
-- Verified Food Database — 120 Items (per 100g)
-- Upsert: delete existing presets with same name, then insert
-- All values are per 100 grams
-- ============================================================

-- First, remove any existing preset entries that match these names
-- (so we replace with the corrected values, no duplicates)
DELETE FROM public.food_inventory WHERE source = 'preset' AND name IN (
  'White Rice (Raw)', 'White Rice (Cooked)', 'Brown Rice (Raw)', 'Brown Rice (Cooked)',
  'Jasmine Rice (Raw)', 'Basmati Rice (Raw)', 'Macaroni / Pasta (Raw)', 'Macaroni / Pasta (Cooked)',
  'Whole Wheat Pasta (Raw)', 'Oats (Rolled, Dry)', 'Quinoa (Dry)', 'Quinoa (Cooked)',
  'Couscous (Dry)', 'Buckwheat (Dry)', 'Barley (Pearled, Dry)',
  'White Bread', 'Whole Wheat Bread', 'Sourdough Bread', 'Rye Bread',
  'Pita Bread (White)', 'Flour Tortilla', 'Corn Tortilla', 'Bagel (Plain)',
  'Potato (Raw, with skin)', 'Potato (Baked, flesh & skin)', 'Sweet Potato (Raw)',
  'Sweet Potato (Baked)', 'Yam (Raw)', 'Cassava / Yuca (Raw)',
  'Chicken Breast (Raw, Skinless)', 'Chicken Breast (Cooked, Roasted)',
  'Chicken Thigh (Raw, Skinless)', 'Chicken Drumstick (Raw, Skinless)',
  'Turkey Breast (Raw)', 'Beef (Ground, 95% Lean, Raw)', 'Beef (Ground, 80% Lean, Raw)',
  'Beef Steak (Sirloin, Raw)', 'Beef Steak (Ribeye, Raw)', 'Pork Chop (Lean, Raw)',
  'Bacon (Pan-fried)', 'Lamb (Leg, Raw)',
  'Tuna (Canned in Water, Drained)', 'Tuna (Canned in Oil, Drained)', 'Tuna (Fresh, Raw)',
  'Salmon (Atlantic, Raw)', 'Tilapia (Raw)', 'Cod (Raw)', 'Shrimp (Raw)',
  'Crab Meat (Cooked)', 'Lobster (Cooked)', 'Sardines (Canned in Oil)',
  'Lentils (Dry)', 'Lentils (Cooked)', 'Chickpeas (Dry)', 'Chickpeas (Cooked/Canned)',
  'Black Beans (Dry)', 'Black Beans (Cooked)', 'Kidney Beans (Cooked)',
  'Edamame (Cooked)', 'Tofu (Firm)', 'Tempeh',
  'Eggs (Raw, Whole)', 'Egg Whites (Raw)', 'Milk (Whole, 3.25%)', 'Milk (Skim, 0%)',
  'Almond Milk (Unsweetened)', 'Soy Milk (Unsweetened)', 'Oat Milk (Unsweetened)',
  'Greek Yogurt (Non-fat, Plain)', 'Yogurt (Whole Milk, Plain)',
  'Cottage Cheese (Low Fat, 2%)', 'Cheddar Cheese', 'Mozzarella (Part Skim)',
  'Parmesan Cheese (Grated)', 'Feta Cheese',
  'Butter (Salted)', 'Ghee (Clarified Butter)', 'Olive Oil (Extra Virgin)',
  'Coconut Oil', 'Avocado Oil', 'Vegetable Oil',
  'Peanut Butter (Natural, No Sugar)', 'Almond Butter (Plain)', 'Almonds (Raw)',
  'Walnuts (Raw)', 'Cashews (Raw)', 'Peanuts (Dry Roasted)', 'Pistachios (Raw)',
  'Macadamia Nuts (Raw)', 'Chia Seeds', 'Flaxseed (Ground)', 'Hemp Seeds', 'Sunflower Seeds',
  'Avocado (Raw)', 'Broccoli (Raw)', 'Spinach (Raw)', 'Kale (Raw)', 'Carrots (Raw)',
  'Tomato (Raw)', 'Bell Pepper (Red, Raw)', 'Onion (Raw)', 'Garlic (Raw)',
  'Mushrooms (White, Raw)', 'Zucchini (Raw)', 'Cucumber (Raw, with peel)',
  'Celery (Raw)', 'Asparagus (Raw)', 'Cauliflower (Raw)', 'Cabbage (Green, Raw)',
  'Brussels Sprouts (Raw)', 'Green Beans (Raw)',
  'Banana (Raw)', 'Apple (Raw, with skin)', 'Orange (Raw)', 'Grapes (Red/Green, Raw)',
  'Strawberries (Raw)', 'Blueberries (Raw)', 'Raspberries (Raw)', 'Blackberries (Raw)',
  'Watermelon (Raw)', 'Cantaloupe (Raw)', 'Pineapple (Raw)', 'Mango (Raw)',
  'Peach (Raw)', 'Plum (Raw)', 'Cherry (Sweet, Raw)', 'Pear (Raw)', 'Kiwi (Raw)', 'Lemon (Raw)',
  'Honey', 'Maple Syrup', 'White Sugar (Granulated)', 'Brown Sugar',
  'Dark Chocolate (70-85% Cacao)', 'Milk Chocolate'
);

-- Now insert all 120 verified foods as global presets
INSERT INTO public.food_inventory (user_id, name, category, kcal_per_100g, protein, carbs, fat, source) VALUES
-- ═══════════════ Grains & Pasta ═══════════════
(NULL, 'White Rice (Raw)',           'Grains & Pasta', 365, 7.1, 80.0, 0.7, 'preset'),
(NULL, 'White Rice (Cooked)',        'Grains & Pasta', 130, 2.7, 28.0, 0.3, 'preset'),
(NULL, 'Brown Rice (Raw)',           'Grains & Pasta', 367, 7.5, 76.2, 3.3, 'preset'),
(NULL, 'Brown Rice (Cooked)',        'Grains & Pasta', 112, 2.6, 23.5, 0.9, 'preset'),
(NULL, 'Jasmine Rice (Raw)',         'Grains & Pasta', 365, 7.1, 80.0, 0.6, 'preset'),
(NULL, 'Basmati Rice (Raw)',         'Grains & Pasta', 365, 7.1, 79.0, 0.6, 'preset'),
(NULL, 'Macaroni / Pasta (Raw)',     'Grains & Pasta', 371, 13.0, 74.7, 1.5, 'preset'),
(NULL, 'Macaroni / Pasta (Cooked)',  'Grains & Pasta', 157, 5.8, 30.7, 0.9, 'preset'),
(NULL, 'Whole Wheat Pasta (Raw)',    'Grains & Pasta', 348, 14.6, 71.3, 1.6, 'preset'),
(NULL, 'Oats (Rolled, Dry)',         'Grains & Pasta', 389, 16.9, 66.3, 6.9, 'preset'),
(NULL, 'Quinoa (Dry)',               'Grains & Pasta', 368, 14.1, 64.2, 6.1, 'preset'),
(NULL, 'Quinoa (Cooked)',            'Grains & Pasta', 120, 4.4, 21.3, 1.9, 'preset'),
(NULL, 'Couscous (Dry)',             'Grains & Pasta', 376, 12.8, 77.4, 0.6, 'preset'),
(NULL, 'Buckwheat (Dry)',            'Grains & Pasta', 343, 13.3, 71.5, 3.4, 'preset'),
(NULL, 'Barley (Pearled, Dry)',      'Grains & Pasta', 352, 9.9, 77.7, 1.2, 'preset'),

-- ═══════════════ Breads & Tortillas ═══════════════
(NULL, 'White Bread',                'Breads & Tortillas', 265, 8.8, 49.0, 3.2, 'preset'),
(NULL, 'Whole Wheat Bread',          'Breads & Tortillas', 252, 12.4, 42.7, 3.5, 'preset'),
(NULL, 'Sourdough Bread',            'Breads & Tortillas', 289, 11.9, 56.4, 1.8, 'preset'),
(NULL, 'Rye Bread',                  'Breads & Tortillas', 259, 8.5, 48.0, 3.3, 'preset'),
(NULL, 'Pita Bread (White)',         'Breads & Tortillas', 275, 9.1, 55.7, 1.2, 'preset'),
(NULL, 'Flour Tortilla',             'Breads & Tortillas', 297, 8.0, 49.3, 7.5, 'preset'),
(NULL, 'Corn Tortilla',              'Breads & Tortillas', 218, 5.7, 45.4, 2.8, 'preset'),
(NULL, 'Bagel (Plain)',              'Breads & Tortillas', 250, 10.2, 50.8, 1.5, 'preset'),

-- ═══════════════ Root Vegetables ═══════════════
(NULL, 'Potato (Raw, with skin)',        'Root Vegetables', 77, 2.0, 17.5, 0.1, 'preset'),
(NULL, 'Potato (Baked, flesh & skin)',   'Root Vegetables', 93, 2.5, 21.2, 0.1, 'preset'),
(NULL, 'Sweet Potato (Raw)',             'Root Vegetables', 86, 1.6, 20.1, 0.1, 'preset'),
(NULL, 'Sweet Potato (Baked)',           'Root Vegetables', 90, 2.0, 20.7, 0.2, 'preset'),
(NULL, 'Yam (Raw)',                      'Root Vegetables', 118, 1.5, 27.9, 0.2, 'preset'),
(NULL, 'Cassava / Yuca (Raw)',           'Root Vegetables', 160, 1.4, 38.1, 0.3, 'preset'),

-- ═══════════════ Meats & Poultry ═══════════════
(NULL, 'Chicken Breast (Raw, Skinless)',     'Meats & Poultry', 120, 22.5, 0.0, 2.6, 'preset'),
(NULL, 'Chicken Breast (Cooked, Roasted)',   'Meats & Poultry', 165, 31.0, 0.0, 3.6, 'preset'),
(NULL, 'Chicken Thigh (Raw, Skinless)',      'Meats & Poultry', 135, 19.5, 0.0, 5.7, 'preset'),
(NULL, 'Chicken Drumstick (Raw, Skinless)',  'Meats & Poultry', 120, 19.1, 0.0, 4.8, 'preset'),
(NULL, 'Turkey Breast (Raw)',                'Meats & Poultry', 114, 23.7, 0.0, 1.5, 'preset'),
(NULL, 'Beef (Ground, 95% Lean, Raw)',       'Meats & Poultry', 137, 21.4, 0.0, 5.0, 'preset'),
(NULL, 'Beef (Ground, 80% Lean, Raw)',       'Meats & Poultry', 254, 17.2, 0.0, 20.0, 'preset'),
(NULL, 'Beef Steak (Sirloin, Raw)',          'Meats & Poultry', 146, 21.6, 0.0, 5.9, 'preset'),
(NULL, 'Beef Steak (Ribeye, Raw)',           'Meats & Poultry', 291, 15.0, 0.0, 25.0, 'preset'),
(NULL, 'Pork Chop (Lean, Raw)',              'Meats & Poultry', 120, 21.1, 0.0, 3.3, 'preset'),
(NULL, 'Bacon (Pan-fried)',                  'Meats & Poultry', 541, 37.0, 1.4, 42.0, 'preset'),
(NULL, 'Lamb (Leg, Raw)',                    'Meats & Poultry', 140, 20.4, 0.0, 5.8, 'preset'),

-- ═══════════════ Seafood ═══════════════
(NULL, 'Tuna (Canned in Water, Drained)',  'Seafood', 116, 25.5, 0.0, 0.8, 'preset'),
(NULL, 'Tuna (Canned in Oil, Drained)',    'Seafood', 198, 29.1, 0.0, 8.2, 'preset'),
(NULL, 'Tuna (Fresh, Raw)',                'Seafood', 144, 23.3, 0.0, 4.9, 'preset'),
(NULL, 'Salmon (Atlantic, Raw)',           'Seafood', 208, 20.4, 0.0, 13.4, 'preset'),
(NULL, 'Tilapia (Raw)',                    'Seafood', 96, 20.1, 0.0, 1.7, 'preset'),
(NULL, 'Cod (Raw)',                        'Seafood', 82, 17.8, 0.0, 0.7, 'preset'),
(NULL, 'Shrimp (Raw)',                     'Seafood', 85, 20.1, 0.0, 0.5, 'preset'),
(NULL, 'Crab Meat (Cooked)',               'Seafood', 82, 18.1, 0.0, 0.7, 'preset'),
(NULL, 'Lobster (Cooked)',                 'Seafood', 89, 19.0, 0.0, 0.9, 'preset'),
(NULL, 'Sardines (Canned in Oil)',         'Seafood', 208, 24.6, 0.0, 11.5, 'preset'),

-- ═══════════════ Legumes & Plant Proteins ═══════════════
(NULL, 'Lentils (Dry)',                'Legumes & Plant Proteins', 353, 24.6, 60.1, 1.1, 'preset'),
(NULL, 'Lentils (Cooked)',             'Legumes & Plant Proteins', 116, 9.0, 20.1, 0.4, 'preset'),
(NULL, 'Chickpeas (Dry)',              'Legumes & Plant Proteins', 378, 20.5, 63.0, 6.0, 'preset'),
(NULL, 'Chickpeas (Cooked/Canned)',    'Legumes & Plant Proteins', 164, 8.9, 27.4, 2.6, 'preset'),
(NULL, 'Black Beans (Dry)',            'Legumes & Plant Proteins', 341, 21.6, 62.4, 1.4, 'preset'),
(NULL, 'Black Beans (Cooked)',         'Legumes & Plant Proteins', 132, 8.9, 23.7, 0.5, 'preset'),
(NULL, 'Kidney Beans (Cooked)',        'Legumes & Plant Proteins', 127, 8.7, 22.8, 0.5, 'preset'),
(NULL, 'Edamame (Cooked)',             'Legumes & Plant Proteins', 121, 11.9, 8.9, 5.2, 'preset'),
(NULL, 'Tofu (Firm)',                  'Legumes & Plant Proteins', 144, 15.8, 2.8, 8.7, 'preset'),
(NULL, 'Tempeh',                       'Legumes & Plant Proteins', 192, 20.3, 7.6, 10.8, 'preset'),

-- ═══════════════ Dairy & Eggs ═══════════════
(NULL, 'Eggs (Raw, Whole)',                'Dairy & Eggs', 143, 12.6, 0.7, 9.5, 'preset'),
(NULL, 'Egg Whites (Raw)',                 'Dairy & Eggs', 52, 10.9, 0.7, 0.2, 'preset'),
(NULL, 'Milk (Whole, 3.25%)',              'Dairy & Eggs', 61, 3.2, 4.8, 3.3, 'preset'),
(NULL, 'Milk (Skim, 0%)',                  'Dairy & Eggs', 34, 3.4, 5.0, 0.1, 'preset'),
(NULL, 'Almond Milk (Unsweetened)',        'Dairy & Eggs', 15, 0.4, 0.3, 1.2, 'preset'),
(NULL, 'Soy Milk (Unsweetened)',           'Dairy & Eggs', 33, 2.9, 1.2, 1.8, 'preset'),
(NULL, 'Oat Milk (Unsweetened)',           'Dairy & Eggs', 48, 1.2, 6.8, 2.1, 'preset'),
(NULL, 'Greek Yogurt (Non-fat, Plain)',    'Dairy & Eggs', 59, 10.3, 3.6, 0.4, 'preset'),
(NULL, 'Yogurt (Whole Milk, Plain)',       'Dairy & Eggs', 61, 3.5, 4.7, 3.3, 'preset'),
(NULL, 'Cottage Cheese (Low Fat, 2%)',     'Dairy & Eggs', 82, 11.0, 4.3, 2.3, 'preset'),
(NULL, 'Cheddar Cheese',                   'Dairy & Eggs', 403, 24.9, 1.3, 33.1, 'preset'),
(NULL, 'Mozzarella (Part Skim)',           'Dairy & Eggs', 254, 24.3, 2.8, 15.9, 'preset'),
(NULL, 'Parmesan Cheese (Grated)',         'Dairy & Eggs', 431, 38.5, 4.1, 28.6, 'preset'),
(NULL, 'Feta Cheese',                      'Dairy & Eggs', 264, 14.2, 4.1, 21.3, 'preset'),

-- ═══════════════ Fats & Oils ═══════════════
(NULL, 'Butter (Salted)',            'Fats & Oils', 717, 0.8, 0.1, 81.1, 'preset'),
(NULL, 'Ghee (Clarified Butter)',    'Fats & Oils', 900, 0.0, 0.0, 100.0, 'preset'),
(NULL, 'Olive Oil (Extra Virgin)',   'Fats & Oils', 884, 0.0, 0.0, 100.0, 'preset'),
(NULL, 'Coconut Oil',                'Fats & Oils', 862, 0.0, 0.0, 100.0, 'preset'),
(NULL, 'Avocado Oil',                'Fats & Oils', 884, 0.0, 0.0, 100.0, 'preset'),
(NULL, 'Vegetable Oil',              'Fats & Oils', 884, 0.0, 0.0, 100.0, 'preset'),

-- ═══════════════ Nuts & Seeds ═══════════════
(NULL, 'Peanut Butter (Natural, No Sugar)', 'Nuts & Seeds', 588, 25.1, 20.0, 50.4, 'preset'),
(NULL, 'Almond Butter (Plain)',              'Nuts & Seeds', 614, 21.0, 18.8, 55.5, 'preset'),
(NULL, 'Almonds (Raw)',                      'Nuts & Seeds', 579, 21.1, 21.6, 49.9, 'preset'),
(NULL, 'Walnuts (Raw)',                      'Nuts & Seeds', 654, 15.2, 13.7, 65.2, 'preset'),
(NULL, 'Cashews (Raw)',                      'Nuts & Seeds', 553, 18.2, 30.2, 43.8, 'preset'),
(NULL, 'Peanuts (Dry Roasted)',              'Nuts & Seeds', 585, 23.7, 21.3, 49.7, 'preset'),
(NULL, 'Pistachios (Raw)',                   'Nuts & Seeds', 562, 20.2, 27.2, 45.3, 'preset'),
(NULL, 'Macadamia Nuts (Raw)',               'Nuts & Seeds', 718, 7.9, 13.8, 75.8, 'preset'),
(NULL, 'Chia Seeds',                         'Nuts & Seeds', 486, 16.5, 42.1, 30.7, 'preset'),
(NULL, 'Flaxseed (Ground)',                  'Nuts & Seeds', 534, 18.3, 28.9, 42.2, 'preset'),
(NULL, 'Hemp Seeds',                         'Nuts & Seeds', 553, 31.6, 8.7, 48.8, 'preset'),
(NULL, 'Sunflower Seeds',                    'Nuts & Seeds', 584, 20.8, 20.0, 51.5, 'preset'),

-- ═══════════════ Vegetables & Produce ═══════════════
(NULL, 'Avocado (Raw)',                  'Vegetables & Produce', 160, 2.0, 8.5, 14.7, 'preset'),
(NULL, 'Broccoli (Raw)',                 'Vegetables & Produce', 34, 2.8, 6.6, 0.4, 'preset'),
(NULL, 'Spinach (Raw)',                  'Vegetables & Produce', 23, 2.9, 3.6, 0.4, 'preset'),
(NULL, 'Kale (Raw)',                     'Vegetables & Produce', 49, 4.3, 8.8, 0.9, 'preset'),
(NULL, 'Carrots (Raw)',                  'Vegetables & Produce', 41, 0.9, 9.6, 0.2, 'preset'),
(NULL, 'Tomato (Raw)',                   'Vegetables & Produce', 18, 0.9, 3.9, 0.2, 'preset'),
(NULL, 'Bell Pepper (Red, Raw)',         'Vegetables & Produce', 31, 1.0, 6.0, 0.3, 'preset'),
(NULL, 'Onion (Raw)',                    'Vegetables & Produce', 40, 1.1, 9.3, 0.1, 'preset'),
(NULL, 'Garlic (Raw)',                   'Vegetables & Produce', 149, 6.4, 33.1, 0.5, 'preset'),
(NULL, 'Mushrooms (White, Raw)',         'Vegetables & Produce', 22, 3.1, 3.3, 0.3, 'preset'),
(NULL, 'Zucchini (Raw)',                 'Vegetables & Produce', 17, 1.2, 3.1, 0.3, 'preset'),
(NULL, 'Cucumber (Raw, with peel)',      'Vegetables & Produce', 15, 0.7, 3.6, 0.1, 'preset'),
(NULL, 'Celery (Raw)',                   'Vegetables & Produce', 14, 0.7, 3.0, 0.2, 'preset'),
(NULL, 'Asparagus (Raw)',                'Vegetables & Produce', 20, 2.2, 3.9, 0.1, 'preset'),
(NULL, 'Cauliflower (Raw)',              'Vegetables & Produce', 25, 1.9, 5.0, 0.3, 'preset'),
(NULL, 'Cabbage (Green, Raw)',           'Vegetables & Produce', 25, 1.3, 5.8, 0.1, 'preset'),
(NULL, 'Brussels Sprouts (Raw)',         'Vegetables & Produce', 43, 3.4, 9.0, 0.3, 'preset'),
(NULL, 'Green Beans (Raw)',              'Vegetables & Produce', 31, 1.8, 7.0, 0.2, 'preset'),

-- ═══════════════ Fruits ═══════════════
(NULL, 'Banana (Raw)',                   'Fruits', 89, 1.1, 22.8, 0.3, 'preset'),
(NULL, 'Apple (Raw, with skin)',         'Fruits', 52, 0.3, 13.8, 0.2, 'preset'),
(NULL, 'Orange (Raw)',                   'Fruits', 47, 0.9, 11.8, 0.1, 'preset'),
(NULL, 'Grapes (Red/Green, Raw)',        'Fruits', 69, 0.7, 18.1, 0.2, 'preset'),
(NULL, 'Strawberries (Raw)',             'Fruits', 32, 0.7, 7.7, 0.3, 'preset'),
(NULL, 'Blueberries (Raw)',              'Fruits', 57, 0.7, 14.5, 0.3, 'preset'),
(NULL, 'Raspberries (Raw)',              'Fruits', 52, 1.2, 11.9, 0.7, 'preset'),
(NULL, 'Blackberries (Raw)',             'Fruits', 43, 1.4, 9.6, 0.5, 'preset'),
(NULL, 'Watermelon (Raw)',               'Fruits', 30, 0.6, 7.6, 0.2, 'preset'),
(NULL, 'Cantaloupe (Raw)',               'Fruits', 34, 0.8, 8.2, 0.2, 'preset'),
(NULL, 'Pineapple (Raw)',                'Fruits', 50, 0.5, 13.1, 0.1, 'preset'),
(NULL, 'Mango (Raw)',                    'Fruits', 60, 0.8, 15.0, 0.4, 'preset'),
(NULL, 'Peach (Raw)',                    'Fruits', 39, 0.9, 9.5, 0.3, 'preset'),
(NULL, 'Plum (Raw)',                     'Fruits', 46, 0.7, 11.4, 0.3, 'preset'),
(NULL, 'Cherry (Sweet, Raw)',            'Fruits', 63, 1.1, 16.0, 0.2, 'preset'),
(NULL, 'Pear (Raw)',                     'Fruits', 57, 0.4, 15.2, 0.1, 'preset'),
(NULL, 'Kiwi (Raw)',                     'Fruits', 61, 1.1, 14.7, 0.5, 'preset'),
(NULL, 'Lemon (Raw)',                    'Fruits', 29, 1.1, 9.3, 0.3, 'preset'),

-- ═══════════════ Sugars & Sweets ═══════════════
(NULL, 'Honey',                          'Sugars & Sweets', 304, 0.3, 82.4, 0.0, 'preset'),
(NULL, 'Maple Syrup',                    'Sugars & Sweets', 260, 0.0, 67.0, 0.1, 'preset'),
(NULL, 'White Sugar (Granulated)',       'Sugars & Sweets', 387, 0.0, 100.0, 0.0, 'preset'),
(NULL, 'Brown Sugar',                    'Sugars & Sweets', 380, 0.1, 98.1, 0.0, 'preset'),
(NULL, 'Dark Chocolate (70-85% Cacao)',  'Sugars & Sweets', 598, 7.8, 45.9, 42.6, 'preset'),
(NULL, 'Milk Chocolate',                 'Sugars & Sweets', 535, 7.7, 59.4, 29.7, 'preset');
